name = "Cclib"
uuid = "1f23c3bf-5af7-41b5-853a-cf1bda1c288e"
authors = ["Victor Cano Gil"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
