name = "Cclib"
uuid = "1f23c3bf-5af7-41b5-853a-cf1bda1c288e"
authors = ["Victor Cano Gil"]
version = "1.0.0-DEV"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
