export mol

struct Mol
    # find the doc string in the python class
    # some of the props in the docs might be missing
    aonames::Array{String}
    aooverlaps::Array{Any}
    atombasis::Array{}
    atomcharges::Dict{}
    atomcoords::Array{}
    atommasses::Array{}
    atomnos::Array{}
    atomspins::Dict{}
    ccenergies::Array{}
    charge::Int64
    coreelectrons::Array{}
    dispersionenergies::Array{}
    enthalpy::Float64
    entropy::Float64
    etenergies::Array{}
    etoscs::Array{}
    etdips::Array{}
    etveldips::Array{}
    etmagdips::Array{}
    etrotats::Array{}
    etsecs::Array{}
    etsyms::Array{String}
    freeenergy::Float64
    fonames::Array{String}
    fooverlaps::Array{}
    fragnames::Array{}
    frags::Array{}
    gbasis::Any
    geotargets::Array{}
    geovalues::Array{}
    grads::Array{}
    hessian::Array{}
    homos::Array{}
    metadata::Dict{}
    mocoeffs::Array{}
    moenergies::Array{}
    moments::Array{}
    mosysm::Array{}
    mpenergies::Array{}
    mult::Int64
    natom::Int64
    nbasis::Int64
    nmo::Int64
    nmrtensors::Dict{}
    nocoeffs::Array{}
    nooccnos::Array{}
    nsocoeffs::Array{}
    nsooccnos::Array{}
    optdone::Bool
    optstatus::Array{}
    polarizabilities::Array{}
    pressure::Float64
    scancoords::Array{}
    scanenergies::Array{}
    scannames::Array{}
    scanparm::Array{}
    scfenergies::Array{}
    scftargets::Array{}
    scfvalues::Array{}
    temperature::Float64
    time::Array{}
    transprop::Dict{}
    vibanharms::Array{}
    vibdisps::Array{}
    vibfreqs::Array{}
    vibfconsts::Array{}
    vibirs::Array{}
    vibramans::Array{}
    vibrmasses::Array{}
    vibsyms::Array{String}
    zpve::Float64
end
